dist: trusty
sudo: required
language: node_js
node_js:
  - node 

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - jdk_switcher use oraclejdk8

addons:
  chrome: stable

cache:
  directories:
  - node_modules

before_script:
  - npm install
  - npm install --only=dev
  - npm install -g chromedriver

script:

